### ISSUE TITLE
Error with official docker image

### ISSUE THREAD

**Issue by przemekrcloudity** [Ziemniakoss/sfdx-ci-summary-creator#1]
When running deployment using official docker image (**salesforce/salesforcedx:7.82.1-0-slim**), hook tries to read value  from undefined value.
![image](https://user-images.githubusercontent.com/95613238/174746458-c43adb05-a1ee-402f-9af8-0d4f2a204933.png)

Deployment was run using 
```
sfdx force:source:deploy -w 15 -x manifest/package.xml -l RunAllTestsInOrg -c  -u $SFDX_ALIAS 
```
command

**Comment by Ziemniakoss** [comment]
Its an issue with old docker images for sfdx.
Old versions of sfdx dispatched different structure of event (or empty event) on finished deployment.
