### ISSUE TITLE
[WONT-FIX] Reports not generating for MDAPI and SF commands

### ISSUE THREAD

**Issue by przemekrcloudity** [Ziemniakoss/sfdx-ci-summary-creator#47]
Reports are not generated for 
```sh
sfdx force:mdapi:deploy
```
commands

**Comment by Ziemniakoss** [comment]
And it never will. 
The problem is that neither mdapi commands nor sf deployment commands trigger hooks.
Without them, report can't be generated.
Sorry for inconvenience but there is nothing I can do about this.
