### ISSUE TITLE
Clickable links in Markdown report

### ISSUE THREAD

**Issue by przemekrcloudity** [Ziemniakoss/sfdx-ci-summary-creator#9]
It would be cool to be able to just click name of the component in failed deployments section or class name in coverage section and be redirected to file in IDE.
I believe this can be achieved using 
```
file://
```
protocol. 
It would be even better if the plugin was able to detect if it is running locally or in CI env and create links with proper links accordingly.

**Comment by Ziemniakoss** [comment]
This won't be implemented because it would need logic to detect which protocol should be used for links (`https` for CI systems and `file` for local deployemnts
